services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sftpdb
      POSTGRES_USER: sftpuser
      POSTGRES_PASSWORD: sftppass
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - D:/app/Sends:/app/download
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db-data:
