version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASS}"
      SFTP_HOST: "${SFTP_HOST}"
      SFTP_PORT: "${SFTP_PORT}"
      SFTP_USER: "${SFTP_USER}"
      SFTP_PASS: "${SFTP_PASS}"
      SFTP_DIR: "${SFTP_DIR}"
      LOCAL_DIR: "${LOCAL_DIR:-/data}"
      CSV_PATH: "${CSV_PATH:-/data/download_log.csv}"
    volumes:
      - "${HOST_STORAGE:-./downloads}:${LOCAL_DIR:-/data}"
      LOCAL_DIR: /downloads
      CSV_PATH: /downloads/download_log.csv
    volumes:
      - ./downloads:/downloads
    restart: always
volumes:
  db-data:
