sftp:
  host: ${SFTP_HOST}
  port: ${SFTP_PORT:22}
  username: ${SFTP_USERNAME}
  password: ${SFTP_PASSWORD}
  remote-dir: ${SFTP_REMOTE_DIR:/}
  # Local directory for downloaded files
  # When using docker-compose this value is overridden to /app/download
  local-dir: ${SFTP_LOCAL_DIR:D:/app/Sends}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sftpdb}
    username: ${SPRING_DATASOURCE_USERNAME:sftpuser}
    password: ${SPRING_DATASOURCE_PASSWORD:sftppass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
